services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futsal-ml
    restart: always
    ports:
      - "3003:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - services

networks:
  services:
    external: false
    name: services
    driver: bridge
