services:
  futsal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futsal-dashboard
    restart: always
    ports:
      - "3002:3002"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - services

networks:
  services:
    external: false
    name: services
    driver: bridge
