export { default as Education } from './education.svg?react';
export { default as Students } from './students.svg?react';
export { default as Read } from './read.svg?react';
export { default as Note } from './notes.svg?react';
export { default as College } from './college.svg?react';
export { default as Building } from './buliding.svg?react';
export { default as ArrowDown } from './arrow-down.svg?react';
export { default as EyeOpenSVG } from './eye_open.svg?react';
export { default as EyeCloseSVG } from './eye_close.svg?react';
export { default as MegaMenuIcon } from './megamenu.svg?react';
export { default as ArrowRight } from './arrow-right.svg?react';
export { default as ArrowRightWhite } from './arrow-right-white.svg?react';
export { default as Location } from './location.svg?react';
export { NoteText } from './NoteText';
export { default as Star } from './star.svg?react';
export { default as EducationRounded } from './education_rounded.svg?react';
export { default as SupportRounded } from './support_rounded.svg?react';
export { default as BookRounded } from './book_rounded.svg?react';
export { default as ComputerRounded } from './computer_rounded.svg?react';
export { Clock } from './Clock';
export { ArrowRightRounded } from './ArrowRightRounded';
export { ArrowLeftRounded } from './ArrowLeftRounded';
export { default as MegaMenuGrey } from './megamenu_grey.svg?react';
export { default as AngleDown } from './angle-down.svg?react';
export { default as AngleDownGrey } from './angle-down-grey.svg?react';
export { default as Setting } from './settings.svg?react';
export { default as LogoBackground } from './logo-background.svg?react';
export { default as Calender } from './calendar.svg?react';
export { Call } from './Call';
export { default as User } from './user.svg?react';
export { default as SMS } from './sms.svg?react';
export { EducationLevel } from './EducationLevel';
export { default as Home } from './home.svg?react';
export { default as ArrowDownPrimary } from './arrow-down-primary.svg?react';
export { default as DocumentText } from './document-text.svg?react';
export { default as TickSquare } from './tick-square.svg?react';
export { default as CloseSquare } from './close-square.svg?react';
export { Bookmarks } from './Bookmarks';
export { default as Edit } from './edit.svg?react';
export { default as AvatarDelete } from './avatar-delete-badge.svg?react';
export { default as Upload } from './upload.svg?react';
export { default as ClockPrimary } from './clock-primary.svg?react';
export { default as DocumentTextBlack } from './document-text-black.svg?react';
export { default as AngleRight } from './angle-right.svg?react';
export { default as AngleLeft } from './angle-left.svg?react';
export { default as Trash } from './trash.svg?react';
export { default as Export } from './export.svg?react';
export { default as Search } from './search.svg?react';
export { Bookmarked } from './Bookmarked';
export { default as AngleDownWhite } from './arrow-down-white.svg?react';
export { default as ClipboardText } from './clipboard-text.svg?react';
export { default as CharmCross } from './charm_cross.svg?react';
export { default as CharmTick } from './charm_tick.svg?react';
export { PlayCircle } from './PlayCircle';
export { default as AddressIcon } from './location-primary.svg?react';
export { default as ArrowLeftPrimary } from './arrow-left-primary.svg?react';
export { default as Resend } from './resend.svg?react';
export { Eye } from './Eye';
export { default as LocationWhite } from './location-white.svg?react';
export { default as BookmarkYellow } from './bookmark-yellow.svg?react';
export { default as StarYellow } from './star-yellow.svg?react';
export { CalendarIcon } from './CalendarIcon';
export { StarIconFilled } from './StarIconFilled';
export { StarIcon } from './StarIcon';
export { CashIcon } from './CashIcon';
export { AddIcon } from './AddIcon';
export { SubtractIcon } from './SubtractIcon';
export { AcademicIcon } from './AcademicIcon';
export { PlacementIcon } from './PlacementIcon';
export { SocialLifeIcon } from './SocialLifeIcon';
export { AccomodationIcon } from './AccomodationIcon';
export { InfrastructureIcon } from './InfrastructureIcon';
export { FacultyIcon } from './FacultyIcon';
export { default as Email } from './direct-inbox.svg?react';
export { LogoutIcon } from './LogoutIcon';
export { MessageIcon } from './Message';
export { BellIcon } from './BellIcon';
export { Award } from './Award';
export { Download } from './Download';
export { EyeOutlined } from './EyeOutlined';
export { Radar } from './Radar';
export { BookIcon } from './BookIcon';
export { PlayCircleOutlined } from './PlayCircleOutlined';
export { Volume } from './Volume';
export { default as GalleryIcon } from './gallery.svg?react';
export { default as University } from './university.svg?react';
export { default as School } from './school.svg?react';
export { default as OnlineExam } from './online-exam.svg?react';
export { default as PhysicalExam } from './physical-exam.svg?react';
export { default as MockExamIcon } from './mock-exam.svg?react';
export { default as ForumIcon } from './forum.svg?react';
export { default as ResultIcon } from './results.svg?react';
export { default as CourseIcon } from './courses.svg?react';
export { default as CollegeIcon } from './college-icon.svg?react';
export { default as LandingNote } from './landing-note.svg?react';
export { default as LandingBook } from './landing-books.svg?react';
export { default as HomeWifi } from './home-wifi.svg?react';
export { default as LandingResults } from './landing-results.svg?react';
export { default as Rank } from './rank.svg?react';
export { default as ArrowLeft } from './arrow-left.svg?react';
export { default as Arrowup } from './arrow-up.svg?react';
export { default as LikeIcon } from './like.svg?react';
export { default as ThreeDot } from './tabler_dots.svg?react';
export { default as LikeFilled } from './like-filled.svg?react';
export { default as AddCircle } from './add-circle.svg?react';
export { default as TickCircle } from './tick-circle.svg?react';
export { default as Flag } from './flag.svg?react';
