services:
  backend:
    build: .
    container_name: futsal-backend
    restart: always
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules